### PR TITLE
updated 1-execute-query-mutation

### PR DESCRIPTION
**Pull request by idkjs**
updated 1-execute-query-mutation to using useReducer hook

### CODE REVIEW

**Comment by parkerziegler** [comment]
@idkjs thanks for contributing! It looks like your fork might be out of sync w/ `master` so it's hard for me to see what's going on in this diff. Would you mind re-syncing your fork with master and then re-introducing this commit: https://github.com/FormidableLabs/reason-urql/pull/71/commits/b40aaa6f4aca10c60c26a789526d03e1634c3908 It's looking good in that commit but I want to make sure we get a clean diff that doesn't reintroduce a bunch of commits. Thank you!

**Comment by idkjs** [comment]
Hey @parkerziegler, not sure what exactly it means to re-introduce a commit so this is what I have done, following this [SO post](https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository).

```
# Add the remote, call it "upstream":

git remote add upstream https://github.com/whoever/whatever.git

# Fetch all the branches of that remote into remote-tracking branches,
# such as upstream/master:

git fetch upstream

# Make sure that you're on your master branch:

git checkout master

# Rewrite your master branch so that any commits of yours that
# aren't already in upstream/master are replayed on top of that
# other branch:

git rebase upstream/master
```

What would I have to do next to "re-introduce https://github.com/FormidableLabs/reason-urql/commit/b40aaa6f4aca10c60c26a789526d03e1634c3908"?

Thanks

**Comment by parkerziegler** [comment]
Your steps are perfect. Go ahead and re-open this PR against `master`. I should delete all the old branches hanging around to ensure we don't open PRs against them (I can see how `task/cleanup-examples` seems like the right place 😅). But this can go directly into `master`. Thanks!

**Comment by idkjs** [comment]
Thank you, sir. Done at https://github.com/FormidableLabs/reason-urql/pull/74.

**Pull request closed without merging**
