### PR TITLE
Improved useDynamicMutation API

### PR DESCRIPTION
**Pull request by Schmavery**
Jumping the gun and posting this WIP PR that @sgrove wrote with me today.
This is dependent on a proposed change to graphql_ppx_re (https://github.com/baransu/graphql_ppx_re/pull/48) that would add a `definition` variable containing the query, parse function and a special `composeVariables` function that lets us do cool API things.

Wanted to get some early feedback on the first one (useDynamicMutation) that we converted, but I'm also working on similar changes to useQuery/useMutation etc which could be neat. It seems to work well so far but I'm very interested if people spot any potential issues.

In case anyone is interested, though it looks a little complicated, this shouldn't make it any harder for non-graphql_ppx_re users to use the library. They would have to write something like this:

```reason
useQuery((a => a, "query", fn => fn(Js.Json.null)));

// We could even expose a helper function like this:
let jsonVars = (v, f) => f(v);
useQuery((a => a, "query", jsonVars(Js.Json.null)));

// Or like this..
let makeDefinition = (~parse: Js.Json.t => args, ~query: string) =>
  (parse, query, (f, vars: Js.Json.t) => f(vars));
Hooks.useQuery(Hooks.makeDefinition(~parse=a=>a, ~query="query"), Js.Json.null);
```

### CODE REVIEW

**Comment by parkerziegler** [comment]
I'm pretty excited about this one @Schmavery and @sgrove, this is a really nice API! Thanks for all the hard work! I'd be happy to merge this – would one of you mind updating the API docs while you're here. I'm also thinking it'd be worth it in the near future to write up a short guide on using `reason-urql` w/out `graphql_ppx_re` so we can capture some of the comments from @Schmavery here, but that doesn't feel important for this PR.

**Comment by parkerziegler** [comment]
Also, just let me know when you think it's safe to remove the WIP tag and formally merge this – I noticed that your changes in `graphql_ppx_re` just got merged, but not sure when a new version will get cut and we can formally pick those up.

**Comment by Schmavery** [comment]
@parkerziegler v0.4.0 of graphql_ppx_re got published, so I updated the example to that so that it can build/pass CI.
It looks like it's working so we can merge if you like :)

When I get a chance I'll rebase and finish https://github.com/FormidableLabs/reason-urql/pull/133.
I fixed some docs in this PR but I want to add more details and info about writing code that doesn't use graphql_ppx_re in that PR if that's ok with you.

**Comment by parkerziegler** [comment]
Awesome, thanks so much for updating the docs. And thanks as well @sgrove, really grateful to have your help on this project! Merging now and will read through the other PR tonight.

**Comment by parkerziegler** [comment]
@all-contributors add @sgrove for code, example, ideas and @Schmavery for docs.

**Comment by parkerziegler** [comment]
@all-contributors add @Schmavery for docs.

**Pull request merged**
